from selenium.webdriver.common.by import By

pageTitleText = (By.CSS_SELECTOR, ".main-title h1 span")
dashboardTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/']")
integrationsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/integrations']")
groupsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/groups']")
appsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/apps']")
sobjectsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/sobjects']")
usersTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/users']")
pluginsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/plugins']")
tasksTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/tasks']")
eventsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/events']")
settingsTab = (By.CSS_SELECTOR, ".bkl-nav [href='#/settings']")
totalAppsText = (By.CSS_SELECTOR, ".card-total-apps")
totalAppsCountText = (By.CSS_SELECTOR, ".card-total-apps .usage-count__count")
totalOperationsText = (By.CSS_SELECTOR, ".card-total-operations")
tokenizationText = (By.CSS_SELECTOR, ".card-tokenization")
totalSObjectsText = (By.CSS_SELECTOR, ".card-sobjects")
totalPluginsText = (By.CSS_SELECTOR, ".card-plugins")
hsmGatewayText = (By.CSS_SELECTOR, ".card-hsm")
usageCharts = (By.CSS_SELECTOR, ".card-line-chart__header")
accountSwitcherBtn = (By.CSS_SELECTOR, ".account-switcher__box")
viewAllBtn = (By.CSS_SELECTOR, ".account-switcher-dropdown__btn-view-all")
